{{- if .Values.front.ingress.enabled -}}
{{- $fullName := include "checker.fullname" . -}}
{{- $ingressPath := .Values.front.ingress.path -}}

{{- $dot := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-front
  labels:
    app.kubernetes.io/name: {{ include "checker.name" . }}
    helm.sh/chart: {{ include "checker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.front.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
        - {{ include "checker.frontDomain" . }}
      secretName: {{ template "checker.name" $dot }}-front-cert
  rules:
    - host: {{ include "checker.frontDomain" . }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ template "checker.fullname" $dot }}-front
                port:
                  number: 80
{{- end }}
